global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'orders_service'
    static_configs:
      - targets: ['orders_service:5600']

  - job_name: 'payments_service'
    static_configs:
      - targets: ['payments_service:5700']

  - job_name: 'notifications_service'
    static_configs:
      - targets: ['notifications_service:5800']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gw_service:5863']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s    # <- intervalo pequeno para live updates
    scrape_timeout: 5s

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
